// `pnpm aws:deploy` / `pnpm aws:destroy`: deploy or tear down the Nightlight-<STAGE> stack.
// Deploy writes the stack outputs to apps/tv/src/config.generated.ts (gitignored).
import {existsSync, readFileSync, writeFileSync} from 'node:fs';
import path from 'node:path';
import {AWS_REGION} from '../packages/shared/src/models.ts';
import {stackName, stageName} from '../infra/lib/stage.ts';
import {capture, repoRoot, run} from './lib/util.ts';

const action = process.argv[2];
if (action !== 'deploy' && action !== 'destroy') {
  console.error('Usage: node scripts/aws.ts <deploy|destroy>');
  process.exit(2);
}

const envFile = path.join(repoRoot, '.env');
if (existsSync(envFile)) {
  process.loadEnvFile(envFile);
}
const region = process.env.AWS_REGION || AWS_REGION;
const stage = stageName();
const stack = stackName(stage);
const env = {...process.env, STAGE: stage, AWS_REGION: region};

const identity = capture('aws', ['sts', 'get-caller-identity', '--query', 'Account', '--output', 'text'], {env});
if (!identity.ok) {
  console.error('No working AWS credentials. Run `pnpm preflight` for setup hints.');
  process.exit(1);
}
const account = identity.stdout.trim();
console.log(`Stack ${stack} · account ${account} · ${region}`);

const cdk = (...args: string[]) => run('pnpm', ['--filter', '@nightlight/infra', 'exec', 'cdk', ...args], {env});

if (action === 'destroy') {
  cdk('destroy', stack, '--force');
  process.exit(0);
}

// One-time per account/region: CDK needs its bootstrap stack before the first deploy.
const bootstrapped = capture('aws', ['cloudformation', 'describe-stacks', '--region', region, '--stack-name', 'CDKToolkit'], {env}).ok;
if (!bootstrapped) {
  cdk('bootstrap', `aws://${account}/${region}`);
}

const outputsFile = path.join(repoRoot, 'infra', 'cdk-outputs.json');
cdk('deploy', stack, '--require-approval', 'never', '--outputs-file', outputsFile);

const outputs = JSON.parse(readFileSync(outputsFile, 'utf8'))[stack] as Record<string, string>;
const configPath = path.join(repoRoot, 'apps', 'tv', 'src', 'config.generated.ts');
writeFileSync(
  configPath,
  `// Generated by \`pnpm aws:deploy\` for stack ${stack}. Do not edit; do not commit.\n` +
    `export const API_URL = ${JSON.stringify(outputs.ApiUrl)};\n` +
    `export const ASSETS_URL = ${JSON.stringify(`https://${outputs.AssetsDomain}`)};\n`,
);
console.log(`\n✔ Deployed ${stack}\n  API:    ${outputs.ApiUrl}\n  Assets: https://${outputs.AssetsDomain}\n  Wrote ${path.relative(repoRoot, configPath)}`);
